import matplotlib.pyplot as plt
from wordcloud import WordCloud
import stylecloud
import json
import csv

stylecloud.gen_stylecloud(file_path='output/TF_IDF/output_2022_season3.csv',
                          icon_name='fas fa-shield-alt',
                          colors='white',
                          background_color='black',
                          output_name='output/wordCloud/2022_season3_shield.png',
                          collocations=False)
stylecloud.gen_stylecloud(file_path='output/TF_IDF/output_2022_season3.csv',
                          icon_name='fas fa-bug',
                          colors='white',
                          background_color='black',
                          output_name='output/wordCloud/2022_season3.png',
                          collocations=False)
stylecloud.gen_stylecloud(file_path='output/TF_IDF/output_2022_season4.csv',
                          icon_name='fas fa-shield-alt',
                          colors='white',
                          background_color='black',
                          output_name='output/wordCloud/2022_season4_shield.png',
                          collocations=False)
stylecloud.gen_stylecloud(file_path='output/TF_IDF/output_2022_season4.csv',
                          icon_name='fas fa-bug',
                          colors='white',
                          background_color='black',
                          output_name='output/wordCloud/2022_season4.png',
                          collocations=False)
stylecloud.gen_stylecloud(file_path='output/TF_IDF/output_2023_season1.csv',
                          icon_name='fas fa-shield-alt',
                          colors='white',
                          background_color='black',
                          output_name='output/wordCloud/2023_season1_shield.png',
                          collocations=False)
stylecloud.gen_stylecloud(file_path='output/TF_IDF/output_2023_season1.csv',
                          icon_name='fas fa-bug',
                          colors='white',
                          background_color='black',
                          output_name='output/wordCloud/2023_season1.png',
                          collocations=False)
stylecloud.gen_stylecloud(file_path='output/TF_IDF/output_2023_season2.csv',
                          icon_name='fas fa-shield-alt',
                          colors='white',
                          background_color='black',
                          output_name='output/wordCloud/2023_season2_shield.png',
                          collocations=False)
stylecloud.gen_stylecloud(file_path='output/TF_IDF/output_2023_season2.csv',
                          icon_name='fas fa-bug',
                          colors='white',
                          background_color='black',
                          output_name='output/wordCloud/2023_season2.png',
                          collocations=False)
stylecloud.gen_stylecloud(file_path='output/TF_IDF/output_2023_season3.csv',
                          icon_name='fas fa-shield-alt',
                          colors='white',
                          background_color='black',
                          output_name='output/wordCloud/2023_season3_shield.png',
                          collocations=False)
stylecloud.gen_stylecloud(file_path='output/TF_IDF/output_2023_season3.csv',
                          icon_name='fas fa-bug',
                          colors='white',
                          background_color='black',
                          output_name='output/wordCloud/2023_season3.png',
                          collocations=False)
stylecloud.gen_stylecloud(file_path='output/TF_IDF/output_2023_season4.csv',
                          icon_name='fas fa-shield-alt',
                          colors='white',
                          background_color='black',
                          output_name='output/wordCloud/2023_season4_shield.png',
                          collocations=False)
stylecloud.gen_stylecloud(file_path='output/TF_IDF/output_2023_season4.csv',
                          icon_name='fas fa-bug',
                          colors='white',
                          background_color='black',
                          output_name='output/wordCloud/2023_season4.png',
                          collocations=False)